### PR TITLE
fix data loss and exception

### PR DESCRIPTION
**Pull request by JimWen**

### CODE REVIEW

**Comment by link3280** [comment]
@JimWen Thanks a lot for your PR. It'd be better if you could provide more background information about the problem we need to fix. I've generally gone through the commits, might have a rough idea about the problem. Before code review, I want to make sure we're on the same page. Please collect me if I'm wrong.

- 9e438823c8b09b7a4461e2b532df0d2b0db40b36 Flushes all in-flight data when the writer is close. This is indeed valid because in non-transaction mode, we provided at-least-one semantic. It can do good to batch scenarios where jobs and their in-flight data would not be recovered. However, in transaction mode, we can only flush data on successful checkpoints, so we need to scope this modification to non-transaction mode.
- b2d758b94d27f1bbaf8b3c6e23e0827f270f0114 Delays the first run of flushes to make sure the writer is fully initialized. But I want to make sure currently one extra run seems no harm either? I guess there should only be some empty bulks at the beginning.
- 0884850ecb2cea265d9cc5fbeac1c99d19aaef0e Ensure data consistency by replace DocumentBulk with thread-safe ConcurrentLinkedQueue. I think the current code may be problematic because it allows adding new elements between receiving a checkpoint barrier and performing the snapshot. However, this should lead to data duplication instead of data loss. Can you elaborate more about how it causes data loss?

WDYT?

**Comment by link3280** [comment]
ping @JimWen

**Comment by link3280** [comment]
@JimWen I'll cherry-pick and modify the commits a bit, which would be signed off by you.

**Comment by JimWen** [comment]
> @JimWen I'll cherry-pick and modify the commits a bit, which would be signed off by you.

Oh，sorry for the late reply. Busy at this time, 
9e43882 you are right
b2d758b  the simplest way to replay the exception is just use a very small SINK_FLUSH_INTERVAL like 1ms,  the old code just call function flush in thread scheduledFuture, and if the SINK_FLUSH_INTERVALis too small, flush(in which member var collection is used) will be call before initializeState (in which member var collection is initialized) is call.
0884850 the simplest way to replay the exception is also just use a very small SINK_FLUSH_INTERVAL, i think the problem is  when you call function write ( in which var currentBulk is used) in flink thread, where function snapshot and flush use var currentBulk in other thread, but currentBulk is not lock protected in write function thread.

**Comment by link3280** [comment]
@JimWen Sorry for not responding in time. I might have missed the notification (I was flooded by lots of notifications previously). May I ask if you are still willing to contribute? I should be able to get this PR merged this weekend. Thanks a lot!

**Comment by JimWen** [comment]
> @JimWen Sorry for not responding in time. I might have missed the notification (I was flooded by lots of notifications previously). May I ask if you are still willing to contribute? I should be able to get this PR merged this weekend. Thanks a lot!

Of course, thanks for sharing this project, I will keep an eye on this project and submit some minor revisions if time permits

**Pull request closed without merging**
